sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest
  - php: 7.1
    env: WP_VERSION=latest
  - php: 7.0
    env: WP_VERSION=latest
  - php: 7.2
    env: WP_VERSION=trunk
  - php: 7.1
    env: WP_VERSION=trunk
  - php: 7.0
    env: WP_VERSION=trunk
before_script:
- composer install
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    composer global require "phpunit/phpunit=4.8.*|5.7.*"
  fi
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
  fi
script:
  - phpunit_
after_success:
  - sed -i -e "s/nightly/${TRAVIS_TAG}/" $(basename $TRAVIS_REPO_SLUG).php
  - curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh | bash
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EuIygz0mTGEtMhXqaxL4ALARccec60/OS8odqZeu15GgthSj/yQThnpfOrSstq9WjLIHMsIkzhC/jh1H+S9pPNCrhjgYUo61yuDXTXpqU2px1bGZk0QkcBIU0qhyP9WhjBSfyNlR7FXyOke8qMbISgGTQMtiwmK5XRSITSuNMUjTE6NnYYQF5gins32CJG2sOwJCc5fkm8iuK34GGS5qRiiulUf4+Wi8JfUoCz/AQZSVDw7RJGYKxDLLltruGTg/yOXe/droYi5Socc8XjyJd3w4obEtJU/PNSU+MtY5Q4Vq77O7wtXVXVeJ6cV4gHg+asGZbOmMlB3xrXPTklu9ONZA/FoMr7E05EWX4sneQlZFY2ft2zLcF7yKJo0vvYeBKUbmPhMs+x9Gxg/WIL2kDSEsW7N6wEJhBiydiiYDg0sldB5o3WN+zCuONh7QRst76tn7UzwBv4ZK+n6m6ey9CtDL3VmDY+oDKAVGQjMxwvBgbOLgHoQeD5dQxw9BgXx8v97QjJKfQ/VJiSHnXEQ/Ft9rv9AfF7C8d4elKCprEn8Y53cIX7neCuYIeZvyY/L6XIOT1/ZULLkGUn65f1IMr5uTNTT34jokNSExGFaM7iH6hveg5pcryPRWyWjc1pWXmzb3UfSfj0NicJKrWc2U+zVVXIKmu9W645/2lcuKfgY=
  file: '_redirect.zip'
  on:
    tags: true
    repo: miya0001/_redirect
